services:
  mysqldb:
    image: mysql:8.0.33
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=Triagedb
      - innodb_force_recovery=1
    ports:
      -  3307:3306 #(Puerto para que no entre en conclicto con mysql):(Puerto interno)
    volumes:
      - ./db/db_demo.sql:/docker-entrypoint-initdb.d/db_demo.sql
      # - ./db/data:/var/lib/mysql # Para que se guarden los datos en la carpeta db/data
    networks:
      - app-network

  # backup:
  #   image: ubuntu
  #   build:
  #     context: ./db/
  #   container_name: backup
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./db/backup.sh:/db/backup.sh
  #     - ./db/backups:/db/backups
  #   entrypoint: ["/db/backup.sh"]


  api:
    container_name: server_api_container
    build:
      context: ./server/
    depends_on:
      - mysqldb
    links:
      - mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PORT=3306
      - DB_PASSWORD=1234
      - DB_NAME=Triagedb
      - PORTAPI=3000
      - JWT_SECRET=123
      - EMAIL_USER=Test
      - EMAIL_PASS=Test
      - ALGORITHM=aes-192-cbc
      - PRIVATE_KEY=Password used to generate key
      - SALT=salt
      - SYNC_KEY=n0sNLn0GyiBKRFmLUyOJ
      - PYTHONSERVER=Qssl2u)]EJ,K7J9v+S$U&F.Sab[hpA)qvKSR#n8krNV<l,oT?b=K}0M70]9hZ4/b"O@Ksw
    ports:
      - 3000:3000
    networks:
      - app-network

  # dataanalysisandreports:
  #   container_name: DataAnalysisAndReports_api_container
  #   build:
  #     context: ./DataAnalysisAndReports/src/
  #   depends_on:
  #     - mysqldb
  #   links:
  #     - mysqldb
  #   environment:
  #     - DB_HOST=http://triage.clou6e6kqfyy.us-east-1.rds.amazonaws.com
  #     - DB_USER=usertriage
  #     - DB_PASSWORD=administraciontriage2024
  #     - DB_PORT=3306
  #     - DB_NAME=Triage_db
  #     - DB_CHARSET=latin1
  #     - CHARTS_RESTRICTION=False
  #     - PYTHONSERVER=Qssl2u)]EJ,K7J9v+S$U&F.Sab[hpA)qvKSR#n8krNV<l,oT?b=K}0M70]9hZ4/b"O@Ksw
  #     - APP_HOST=https://triage-hf-6wdp.onrender.com
  #     - APP_KEY=123
  #     - MANAGER_SECRET=TRIAGE_APP_110112_220221
  #   ports:
  #     - 5000:5000
  #   networks:
  #     - app-network

      
  superset:
    image: apache/superset:latest-dev
    container_name: superset_container
    environment:
      SUPERSET_SECRET_KEY: "supersecretkey"
      SQLALCHEMY_DATABASE_URI: "mysql://root:1234@mysqldb:3306/Triagedb"
      SUPERSET_FEATURE_EMBEDDED_SUPERSET: true
      TALISMAN_ENABLED : false
    depends_on:
      - mysqldb
    ports:
      - 8088:8088
    networks:
      - app-network
    volumes:
      - ./superset_home:/app/superset_home
      - ./dashboards:/app/dashboards
      - ./superset/config.py:/app/superset/config.py 
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
    user: root
    entrypoint: >
      /bin/sh -c "
      chmod +x /app/docker-entrypoint.sh &&
      /app/docker-entrypoint.sh &&
      superset run -p 8088 -h 0.0.0.0 --with-threads --reload --debugger"

      # superset import-dashboards -p /app/dashboards/dashboard_export.zip --username admin --dashboard-slug your-dashboard-slug &&
      # superset fab create-user --username guest --firstname Guest --lastname User --email guest@example.com --password guest --role Gamma &&
      # superset fab create-user --username guest --firstname Guest --lastname User --email guest@example.com --password guest --role Public &&  
      # superset set-database-uri --database_name TriageDB --uri 'mysql://usertriage:administraciontriage2024@triage.clou6e6kqfyy.us-east-1.rds.amazonaws.com:3306/Triage_db' &&
      # leer este issue en github para cargar dashboards de forma automatica https://github.com/apache/superset/issues/28692#issuecomment-2337761581

  triageapp:
    container_name: react_app_container
    build:
      context: ./triage-app/
    depends_on:
      - mysqldb
      - api
    links:
      - mysqldb
      - api
    ports:
      - 5173:5173
    networks:
      - app-network

  mysql_refactor:
    image: mysql:8.0.33
    container_name: mysql_refactor_container
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=triage-refactor-db
    ports:
      - 3309:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  nestjs_refactor:
    build: ./nestjs-refactor
    container_name: nestjs_refactor
    restart: always
    depends_on:
      - mysql_refactor
    environment:
      DATABASE_HOST: mysql_refactor
      DATABASE_PORT: 3306 # Al estar en la misma red el puerto debe ser 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: "1234"
      DATABASE_NAME: triage-refactor-db
      SYNCHRONIZE: "false"
      PRODUCTION: "false"
      PORT: 3010 
    ports:
      - 3010:3010
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
