services:
  mysqldb:
    image: mysql:8.0.33
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=Triage_db
    ports:
      - 3307:3306
    volumes:
      - ./db/db_demo.sql:/docker-entrypoint-initdb.d/db_demo.sql
    networks:
      - app-network

  # backup:
  #   image: ubuntu
  #   build:
  #     context: ./db/
  #   container_name: backup
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./db/backup.sh:/db/backup.sh
  #     - ./db/backups:/db/backups
  #   entrypoint: ["/db/backup.sh"]


  api:
    container_name: server_api_container
    build:
      context: ./server/
    depends_on:
      - mysqldb
    links:
      - mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PORT=3306
      - DB_PASSWORD=1234
      - DB_NAME=Triagedb
      - PORTAPI=3000
      - JWT_SECRET=123
      - EMAIL_USER=Test
      - EMAIL_PASS=Test
      - ALGORITHM=aes-192-cbc
      - PRIVATE_KEY=Password used to generate key
      - SALT=salt
      - PYTHONSERVER=Qssl2u)]EJ,K7J9v+S$U&F.Sab[hpA)qvKSR#n8krNV<l,oT?b=K}0M70]9hZ4/b"O@Ksw
    ports:
      - 3000:3000
    networks:
      - app-network

  dataanalysisandreports:
    container_name: DataAnalysisAndReports_api_container
    build:
      context: ./DataAnalysisAndReports/src/
    depends_on:
      - mysqldb
    links:
      - mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PORT=3306
      - DB_PASSWORD=1234
      - DB_NAME=Triagedb
      - DB_CHARSET=latin1
      - CHARTS_RESTRICTION=False
      - PYTHONSERVER=Qssl2u)]EJ,K7J9v+S$U&F.Sab[hpA)qvKSR#n8krNV<l,oT?b=K}0M70]9hZ4/b"O@Ksw
      - APP_HOST=192.168.0.83  
      - APP_PORT=5000
    ports:
      - 5000:5000
    networks:
      - app-network
      

  triageapp:
    container_name: react_app_container
    build:
      context: ./triage-app/
    depends_on:
      - mysqldb
      - api
    links:
      - mysqldb
      - api
    ports:
      - 5173:5173
    networks:
      - app-network


networks:
  app-network:
    driver: bridge