### Get all patients
GET http://localhost:3000/patient

### Get patient by id
GET http://localhost:3000/patient/1

### Post a new patient
POST http://localhost:3000/users
content-type: application/json

{
    "patient_name": "New",
    "date_of_birth": "1990-01-15T02:00:00.000Z",
    "patient_box": "Box1",
    "patient_status": 1,
    "doctor_id": 1,
    "nurse_id": 1,
}

### Delete a patient
DELETE http://localhost:3000/patient/2

### Update a patient
PATCH http://localhost:3000/patient/1
Content-Type: application/json

{
  "patient_status": false
}