FROM ubuntu:latest

# Instalar Docker
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io

# Copiar tu script
COPY backup.sh /backup.sh

# Hacer ejecutable el script
RUN chmod +x /backup.sh

# Ejecutar el script
CMD ["backup.sh"]
