### Get all patients
GET http://localhost:3000/patient

### Search Case 1: Search by name
GET http://localhost:3000/patient/search?user_name=John%20Doe

### Search Case 2: Search by date of birth
GET http://localhost:3000/patient/search?date=1990-01-15

### Search Case 3: Search by name and date of birth
GET http://localhost:3000/patient/search?user_name=John%20Doe&date=1990-01-15

### Get all patients awaiting admission
GET http://localhost:3000/patient/search/awaiting-admission

### Get all patients awaiting internation
GET http://localhost:3000/patient/search/awaiting-internation

### Post a new patient
POST http://localhost:3000/patient
content-type: application/json

{
  "patient_name": "Nuevo Paciente",
  "date_of_birth": "2000-01-01",
  "entry_time": "2023-01-01 10:00:00",
  "exit_time": null,
  "patient_triage_time": "2023-01-01 10:15:00",
  "patient_triage_level": 2,
  "patient_box": "CONSULTORIO",
  "patient_status": "EN ESPERA",
  "patient_problem": "Síntomas generales",
  "patient_medication": "Paracetamol",
  "doctor_id": 1,
  "nurse_id": 2,
  "box_id": 1
}

### Delete a patient (TODO)
DELETE http://localhost:3000/patient/2

### Update a patient (TODO)
PATCH http://localhost:3000/patient/1
Content-Type: application/json

{
  "patient_status": false
}